unless Rails.env.production?
  namespace :dev do
    desc "Drops, creates, migrates, and adds sample data to database"
    task reset: [
      :environment,
      "db:drop",
      "db:schema:cache:clear",
      "db:create",
      "db:migrate",
      "dev:sample_data",
    ]

    desc "Fill the database tables with some sample data"
    task sample_data: :environment do
      if Rails.env.development?
        User.create(
          first_name: "Alice",
          last_name: "Smith",
          email: "alice@smith.com",
          password: "password",
          role: "admin",
          bio: Faker::Lorem.paragraph,
        )

        # Seed Categories table with sample data
        10.times do
          Category.create(
            name: Faker::Commerce.department,
            description: Faker::Lorem.sentence,
            subcategory: Faker::Commerce.department,
          )
        end

        25.times do
          Subcategory.create(
            name: Faker::Commerce.department,
            description: Faker::Lorem.sentence,
            category: Category.all.sample,
          )
        end

        # Seed InventoryTransactions table with sample data
        20.times do
          InventoryTransaction.create(
            transaction_type: %w(incoming_return outgoing_return incoming_sale outgoing_sale).sample,
            quantity: Faker::Number.between(from: 1, to: 100),
          )
        end

        # Seed Locations table with sample data
        10.times do
          StorageLocation.create(
            name: Faker::Address.community,
            description: Faker::Lorem.sentence,
            address: Faker::Address.full_address,
          )
        end

        # Create an array with 10 instances of addresses from Location.address.sample
        location_addresses = StorageLocation.pluck(:address).sample(10)

        # Create an array with 5 instances of addresses generated by Faker
        faker_addresses = 5.times.map { Faker::Address.full_address }

        # Combine the arrays
        addresses = location_addresses + faker_addresses

        # Seed Orders table with sample data
        15.times do
          sending_address = addresses.sample
          receiving_address = addresses.sample

          # Ensure that at least one of the addresses matches a Location.address
          while !(StorageLocation.exists?(address: sending_address) || StorageLocation.exists?(address: receiving_address))
            sending_address = addresses.sample
            receiving_address = addresses.sample
          end
          10.times do
            o = Order.create(
              expected_delivery: Faker::Time.forward(days: 30),
              status: %w(delivered processing in_transit).sample,
              description: "#{["FedEx", "UPS", "USPS"].sample} tracking ##{rand(1000000000000)}",
              sending_address: sending_address,
              receiving_address: receiving_address,
            )

            puts o
          end
        end

        # Seed Reports table with sample data (probably not gonna use this but just in case)
        10.times do
          Report.create(
            report_type: Faker::Lorem.word,
            date: Faker::Time.backward(days: 90),
            data_criteria: Faker::Lorem.sentence,
          )
        end

        # Seed Roles table with sample data (probably not gonna use this either but just in case)
        # 5.times do
        #   Role.create(
        #     admin_id: Faker::Number.between(from: 1, to: 10),
        #     staff_id: Faker::Number.between(from: 1, to: 10),
        #     manager_id: Faker::Number.between(from: 1, to: 10),
        #   )
        # end

        # Seed Suppliers table with sample data

        10.times do
          s = Supplier.create(
            name: Faker::Company.name,
            address: Faker::Address.full_address,
            contact_info: Faker::Internet.email,
            description: Faker::Company.catch_phrase,
            standing: %w(good arrears).sample,
          )
        end

        50.times do
          p = Product.create(
            name: Faker::Commerce.product_name,
            description: Faker::Lorem.sentence,
            sku: Faker::Number.number(digits: 6),
            price: Faker::Commerce.price(range: 10.0..100.0),
            stock_quantity: Faker::Number.between(from: 0, to: 1000),
            category_id: Faker::Number.between(from: 1, to: 9),
            subcategory_id: Faker::Number.between(from: 1, to: 24),
            supplier_id: Faker::Number.between(from: 1, to: 9),
            order_id: Order.all.sample.id,
          )
          if p.persisted?
            puts p.inspect
          else
            puts p.errors.full_messages
          end
        end

        # Seed Users table with sample data
        20.times do
          User.create(
            email: Faker::Internet.email,
            password: "password",
            role: %w(admin staff manager).sample,
            bio: Faker::Lorem.paragraph,
            first_name: Faker::Name.first_name,
            last_name: Faker::Name.last_name,
            # image: Faker::Avatar.image,
          )
        end

        # Seed OrderProducts table with sample data
        90.times do
          op = OrderProduct.create(
            quantity_ordered: Faker::Number.between(from: 1, to: 20),
            shipping_cost: Faker::Number.between(from: 1, to: 30),
            order_id: Order.all.sample.id,
            product_id: Product.all.sample.id,
          )
          if op.persisted?
            puts op.inspect
          else
            puts op.errors.full_messages
          end
        end

        puts "Sample data has been seeded into the database."
      end
    end
  end
end
