require:
  - rubocop-rails-accessibility

inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
  DisplayCopNames: true
  SuggestExtensions: false

Rails:
  Enabled: true
